version: '3.8'

services:

  backend:
    build: ./deployment/backend
#    ports:
#      - 5000:5000
    volumes:
      - ./services/backend:/app
    command: uvicorn app:app --reload --host 0.0.0.0 --port 5000
